### ISSUE TITLE
.Chatted event missing "Event" parameter

### ISSUE THREAD

**Issue by indexxing** [GoldenretriverYT/polytoria-luals-addon#2]
https://docs.polytoria.com/objects/game/Player/#Chatted

Event = { Player: Player, Message: string, Canceled: boolean }

I would have added but I'm not sure how to make it so that .Player, .Message, and .Canceled autocomplete if you are accessing the event object.

**Comment by retrievaaaa** [comment]
geeked up

**Comment by retrievaaaa** [comment]
forgot about it (gonna forget about it again)
